name: generate 3d chart for profile contributions

on:
    schedule:
        - cron: "0 19 * * *"
        - cron: "0 10 * * *"

    # allows to manually run the job at any time
    workflow_dispatch:

    # run on every push on the main branch
    # don't forget to change if you're using 'master' branch
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 100
        name: generate-github-profile-3d-contrib
        steps:
            - uses: actions/checkout@v3
            - uses: yoshi389111/github-profile-3d-contrib@0.7.1
              env:
                  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
                  USERNAME: ${{ github.repository_owner }}
            - name: Commit & Push
              run: |
                  git config user.name "immunity39"
                  git config user.email "so_kaicyo@icloud.com"
                  git add -A .
                  git commit -m "generated"
                  git push
